import type { Metadata } from "next";
import "../styles/globals.css";
import localFont from 'next/font/local'

const myFont = localFont({ src: '../fonts/LufgaRegular.ttf' })

export const metadata: Metadata = {
  title: "CHKR",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={myFont.className}>{children}</body>
    </html>
  );
}
